version: '2.3'
services:
  boketai:
    build: docker/boketai
    runtime: nvidia
    ports:
      - "6006:6006"
    volumes:
      - .:/workspace
      - /mnt/storage:/storage
  knp:
    build: docker/knp
    volumes:
      - .:/workspace
