FROM tensorflow/tensorflow:1.6.0-gpu-py3
RUN apt-get update && apt-get install -y -f locales
RUN locale-gen ja_JP.UTF-8
ENV LANG ja_JP.UTF-8
ENV LC_CTYPE ja_JP.UTF-8
RUN localedef -f UTF-8 -i ja_JP ja_JP.utf8
WORKDIR /workspace